db.getCollection("song_nlp2").drop();
db.getCollection("songoid").aggregate(
    [{$lookup: {
        from: 'song',
        localField: '_id',
        foreignField: '_id',
        as: 'new_field'
            }},
        {$unwind: '$new_field'},
        {$project: {
            _id: 1,
            abstract: 1,
            albumTitle: 1,
            animux_content: 1,
            animux_contents: 1,
            animux_path: 1,
            animux_paths: 1,
            name: 1,
            availableCountries: 1,
            award: 1,
            begin: 1,
            bpm: 1,
            chords_metadata: 1,
            deezer_mapping: 1,
            disambiguation: 1,
            end: 1,
            explicitLyrics: 1,
	explicit_content_lyrics:1,
            format: 1,
            gain: 1,
            genre: 1,
            id_album: 1,
            id_album_deezer: 1,
            id_artist_deezer: 1,
            id_song_deezer: 1,
            id_song_musicbrainz: 1,
            isClassic: 1,
            isrc: 1,
            language: 1,
            language_detect: 1,
            length: 1,
            lengthAlbum: 1,
            multitrack_file: 1,
            multitrack_path: 1,
            newPreview: 1,
            notes: 1,
            position: 1,
            preview: 1,
            producer: 1,
            publicationDate: 1,
            publicationDateAlbum: 1,
            rank: 1,
            rdf: 1,
            recordLabel: 1,
            recorded: 1,
            releaseDate: 1,
            runtime: 1,
            subject: 1,
            title: 1,
            title_accent_fold: 1,
            urlAllmusic: 1,
            urlAmazon: 1,
            urlDeezer: 1,
            urlGoEar: 1,
            urlHypeMachine: 1,
            urlITunes: 1,
            urlLastFm: 1,
            urlMusicBrainz: 1,
            urlPandora: 1,
            urlSong: 1,
            urlSpotify: 1,
            urlWikipedia: 1,
            urlYouTube: 1,
            writer: 1,
            arousal: '$new_field.arousal',
            arousal_predicted: '$new_field.arousal_predicted',
            album_genre: '$new_field.album_genre',
            explicitLyrics_predicted: '$new_field.explicit_content_lyrics_predicted',
	explicitLyrics_predicted_count: '$new_field.explicit_content_lyrics',
            has_emotion_tags: '$new_field.has_emotion_tags',
            has_social_tags: '$new_field.has_social_tags',
            lastfm_id: '$new_field.lastfm_id',
            valence: '$new_field.valence',
            valence_predicted: '$new_field.valence_predicted',
         }},
         {$out : "song_nlp2"}

], 
    { 
        "allowDiskUse" : true
    }
)
